### ISSUE TITLE
When accordion is collapsed, validation errors like required fields are not visible to user

### ISSUE THREAD

**Issue by texnixe** [Klickmeister/kirby-panel-accordion#1]
The [tab field](https://github.com/afbora/Kirby-Tabs-Field) has solved this usability issue by switching to the tab, I think in the case of accordions, maybe those should be auto-opened when an error occurs?

**Comment by zvaehn** [comment]
Hello texnixe,
thanks for this advice!

I'll come back when i'm a little bit less busy.
